Document: pidgin-typewriter
Title: Debian pidgin-typewriter Manual
Author: <insert document author here>
Abstract: This manual describes what pidgin-typewriter is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pidgin-typewriter/pidgin-typewriter.sgml.gz

Format: postscript
Files: /usr/share/doc/pidgin-typewriter/pidgin-typewriter.ps.gz

Format: text
Files: /usr/share/doc/pidgin-typewriter/pidgin-typewriter.text.gz

Format: HTML
Index: /usr/share/doc/pidgin-typewriter/html/index.html
Files: /usr/share/doc/pidgin-typewriter/html/*.html
